// <auto-generated />
using System;
using FitNance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitNance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004022515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitNance.Models.Authentication.UserLoginModel", b =>
                {
                    b.Property<decimal>("Rowstamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Rowstamp"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rowstamp");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("FitNance.Models.Food.MasterFoodModel", b =>
                {
                    b.Property<string>("FoodId")
                        .HasColumnType("nchar(10)");

                    b.Property<double?>("Calories")
                        .HasColumnType("float");

                    b.Property<double?>("Carbs")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Cholesterol")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Fat")
                        .HasColumnType("float");

                    b.Property<double?>("Fiber")
                        .HasColumnType("float");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("IsCanned")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFastFood")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Protein")
                        .HasColumnType("float");

                    b.Property<decimal>("Rowstamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Rowstamp"));

                    b.Property<double?>("ServingGrams")
                        .HasColumnType("float");

                    b.Property<double?>("ServingSize")
                        .HasColumnType("float");

                    b.Property<string>("ServingUnit")
                        .HasColumnType("varchar(30)");

                    b.Property<double?>("Sodium")
                        .HasColumnType("float");

                    b.Property<double?>("Sugar")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(150)");

                    b.HasKey("FoodId");

                    b.ToTable("Master_Food");
                });

            modelBuilder.Entity("FitNance.Models.ProfileSetup.ProfileSetupResultModel", b =>
                {
                    b.Property<double>("ActivityFactor")
                        .HasColumnType("float");

                    b.Property<string>("ActivityLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("BMR")
                        .HasColumnType("float");

                    b.Property<double>("CalorieAdjustment")
                        .HasColumnType("float");

                    b.Property<string>("FitnessGoalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("TDEE")
                        .HasColumnType("float");

                    b.Property<double>("TargetCalories")
                        .HasColumnType("float");

                    b.Property<double>("TargetCarbs")
                        .HasColumnType("float");

                    b.Property<double>("TargetFat")
                        .HasColumnType("float");

                    b.Property<double>("TargetProtein")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.ToTable("ProfileSetupResults");
                });

            modelBuilder.Entity("FitNance.Models.ProfileSetup.UserProfileModel", b =>
                {
                    b.Property<string>("UserProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActivityLevelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Age")
                        .HasColumnType("float");

                    b.Property<double?>("BMR")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CurrentBMI")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentSavings")
                        .HasColumnType("float");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FitnessGoalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("MonthlyIncome")
                        .HasColumnType("float");

                    b.Property<double?>("SavingsGoal")
                        .HasColumnType("float");

                    b.Property<double?>("TDEE")
                        .HasColumnType("float");

                    b.Property<double?>("TargetCalories")
                        .HasColumnType("float");

                    b.Property<double?>("TargetCarbs")
                        .HasColumnType("float");

                    b.Property<double?>("TargetFat")
                        .HasColumnType("float");

                    b.Property<double?>("TargetProtein")
                        .HasColumnType("float");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("FitNance.Models.ProfileSetup.UserThemeModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryFontColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryFontColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTheme");
                });

            modelBuilder.Entity("FitNance.Models.Setup.ActivityLevelModel", b =>
                {
                    b.Property<string>("ActivityLevelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActivityLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityLevelId");

                    b.ToTable("ActivityLevels");
                });

            modelBuilder.Entity("FitNance.Models.Setup.FoodCategoryModel", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Setup_FoodCategory");
                });

            modelBuilder.Entity("FitNance.Models.Setup.NutritionGoalsModel", b =>
                {
                    b.Property<string>("GoalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoalId");

                    b.ToTable("NutritionGoals");
                });

            modelBuilder.Entity("FitNance.Models.Setup.ServingUnitModel", b =>
                {
                    b.Property<string>("ServingUnitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServingUnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServingUnitId");

                    b.ToTable("ServingUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
